pull_request_title: 'refactor: update translations'
commit_message: 'refactor: update translations'
append_commit_message: false
files:
  - source: /src/main/resources/lang/en_US.json
    translation: /src/main/resources/lang/%locale%.json
