# Database Settings
db:
  type: "hsqldb" # Available types: "hsqldb", "h2", "mysql", "mariadb"
  prefix: "example_" # The table prefix
  host: "127.0.0.1"
  port: 3306
  database: "database_name"
  user: "name"
  pass: "123"
  repair: false
