# Update Checker Settings
update-checker:
  enable: true
  console: true # Post message to console
  op: true # Send update notification to opped players on join

# Translation, specify the language file to use, for example `en-US` which will load `/translations/en-US.yml`
translation: "en-US"