# Database Settings
database:
  # Available types: "sqlite", "h2", "mysql", "mariadb"
  type: "sqlite"
  table-prefix: "example_"

  # Authentication
  host: "localhost"
  port: 3306
  database: "database_name"
  username: "root"
  password: ""

  # Advanced settings (Please don't touch unless you know what you're doing!)
  advanced:
    # Should we try to repair broken migrations to the database
    repair: false

    # Configure the HikariCP connection pool
    connection-pool:
      max-pool-size: 10
      min-idle: 10
      max-lifetime: 180000
      keepalive-time: 60000
      connection-timeout: 20000

    # A list of connection parameters, you can include more by adding them on a new line
    connection-properties:
      useSSL: false
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false

# Message Broker Settings
messenger:
  # Enable or disable the message broker
  # This is only required if you are running the plugin on a server network
  enabled: true

  # How often to poll for new messages (in milliseconds)
  # This value MUST be less than the cleanup-interval, preferably less than 1/3 of it.
  polling-interval: 1000

  # How often to clean up old messages (in milliseconds)
  # This value MUST be greater than the polling-interval, preferably at least 3 times it.
  cleanup-interval: 30000

  # Available types: "sql", "plugin", "redis", "rabbitmq", "nats"
  type: "sql"

  # Shared settings (redis, rabbitmq, nats)
  address: "localhost:6379" # Address can be a single entry, or a list of address entries if you wish to connect to a
  username: ""
  password: ""
  ssl: false

  # RabbitMQ specific settings
  virtual-host: "/"