name: 'Setup JDK'
description: 'Set up JDK'

inputs:
  java-version:
    description: 'Java version'
    required: false
    default: '21'
  distribution:
    description: 'JDK Distribution'
    required: false
    default: 'temurin'

runs:
  using: 'composite'
  steps:
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
