name: 'Setup Gradle'
description: 'Grant execute permissions, validate Gradle wrapper, setup Gradle wrapper'

runs:
  using: 'composite'
  steps:
    - name: Grant execute permissions for Gradle wrapper
      run: chmod +x gradlew
      shell: bash

    - name: Validate Gradle Wrapper Authenticity
      uses: gradle/actions/wrapper-validation@v4

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        add-job-summary: 'on-failure'
