name: Build & Upload Release jar with Gradle

on:
  release:
    types: [ published ]

jobs:
  upload_asset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon

      - name: Upload Release Assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/libs/ExamplePlugin-*.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.event.release.tag_name }}